Add multi-access
SparklingComet/TradeShop pull request #19
Opened 2017-07-27 17:38 UTC by SparklingComet

*Will write a description later*

2017-07-27 19:11 UTC, KillerOfPie requested changes

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +import org.bukkit.*;
If we are importing all of bukkit shouldn't we get rid of the rest of the imports?

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
> -			return;
Why did we lose this return?

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
>  	public void onChestOpen(PlayerInteractEvent e) {
I want to play with this a bit to make it also show the name of the inventory as "Shop" or "Chest" when they open it

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
> +				|| getShopMembers(block).contains(Bukkit.getOfflinePlayer(e.getPlayer().getUniqueId()))) {
We should either have a method that  does both, or have members return all members and owners?

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> -		//	BlockState state = event.getBlock().getState();
This can  go

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!event.getLine(0).equalsIgnoreCase("[BiTrade]")) {
do we want a method for checking these as well, or should we make the isTradeShop methods ignore case so they find these too?

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		} else if (!player.hasPermission(getCreatePerm())) {
should be getCreateBiPerm

2017-07-27 19:11 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!plugin.getAllowedInventories().contains(chest.getType())) {
move this into the try and have it throw an exception so we dont have to do the setlines and no chest message twice

2017-07-27 19:23 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
> -			return;
The method's return type is void and it was the last statement of the if block. After that there is only an else block, so no need for it.

2017-07-27 19:24 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
>  	public void onChestOpen(PlayerInteractEvent e) {
What exactly do you mean by that?

2017-07-27 19:24 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
> +				|| getShopMembers(block).contains(Bukkit.getOfflinePlayer(e.getPlayer().getUniqueId()))) {
Will add a method that returns all members/owners

2017-07-27 19:24 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> -		//	BlockState state = event.getBlock().getState();
Good catch, will remove.

2017-07-27 19:25 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!event.getLine(0).equalsIgnoreCase("[BiTrade]")) {
When I initially wrote the plugin (Idk how it looks like now) it automatically changed the case to [Trade]/[iTrade], so #equalsIgnoreCase was superficial. I am not sure how it works now.

2017-07-27 19:26 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		} else if (!player.hasPermission(getCreatePerm())) {
Uhm... I don't recall changing it... Good catch anyways, will fix.

2017-07-27 19:27 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +import org.bukkit.*;
That was made by my IDE, didn't notice it. Wildcard imports are a *really* bad practice so I will fix this immediately.

2017-07-27 19:27 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!plugin.getAllowedInventories().contains(chest.getType())) {
Will do.

2017-07-27 19:36 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> -		//	BlockState state = event.getBlock().getState();
I thought so.

2017-07-27 19:39 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!plugin.getAllowedInventories().contains(chest.getType())) {
maybe we should create a method in utils to set the lines... I'll add it to the TODO.

2017-07-27 19:50 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!event.getLine(0).equalsIgnoreCase("[BiTrade]")) {
thats for the creation signs(so if a player doesnt cap them) its like that in all the creation files, but only for the first line

2017-07-27 19:51 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/bitrade/BiShopCreateEventListener.java
> +		if (!plugin.getAllowedInventories().contains(chest.getType())) {
we can, would have to pass it the sign the trade type tho

2017-07-27 19:52 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/admin/AdminEventListener.java
> -			return;
k

2017-07-28 07:13 UTC, KillerOfPie requested changes
These need to get fixed before it works, also can you add the commands for adding owners and members. the break command is a good base to start with.

2017-07-28 07:13 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +		Chest c = (Chest) findShopChest(s.getBlock());
Needs to use getState()

2017-07-28 07:13 UTC, KillerOfPie commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +		Chest c = (Chest) findShopChest(s.getBlock());
Needs to use getState()

2017-07-28 07:39 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +		Chest c = (Chest) findShopChest(s.getBlock());
Fixed in [this commit](https://github.com/SparklingComet/TradeShop/pull/19/commits/b4fd175bbadc031d7420a5ae2eeb638209826fc9)

2017-07-28 07:39 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +		Chest c = (Chest) findShopChest(s.getBlock());
Fixed in [this commit](https://github.com/SparklingComet/TradeShop/pull/19/commits/b4fd175bbadc031d7420a5ae2eeb638209826fc9)

2017-07-28 08:48 UTC, SparklingComet commented
I have added the addOwner and removeOwner methods in the last commit, but if someone tries to add someone who is already a member the target will be entered twice. There won't be any undesired effects, but it will take storage space, which is limited.
This will have to be fixed.

2017-07-28 17:22 UTC, KillerOfPie approved these changes

2017-07-28 17:23 UTC, KillerOfPie approved these changes
Looks good, gonna test everything real quick and see how many names we can put in

2017-08-04 06:55 UTC, KillerOfPie submitted a review, later dismissed
Looks good i'm tired AF tho, have we added a check for total users on the chest yet? 
and also a check for if the user is already on the chest when we add them?
also players can be added that don't actually exist, are we going to check for that or just leave it to the players, there are no errors if a name is incorrect.

2017-08-04 15:10 UTC, SparklingComet commented
Writing from my phone, so I cannot make any changes right now.

> Looks good i'm tired AF tho, have we added a check for total users on the chest yet?
and also a check for if the user is already on the chest when we add them?
also players can be added that don't actually exist, are we going to check for that or just leave it to the players, there are no errors if a name is incorrect.

getShopMembers() returns all members, regardless of whether they're owners or not. You can distinguish owners from members by checking whether getShopOwners also contains that OfflinePlayer.

There is no check like that. I believe it was added to the todo list, but it may have been accidentally moved to 'Completed' by me. We should definitely add it before merging, if you can do that (I cannot), that would be excellent.

Lastly, that can stay as it is, at least in my opinion. I also planned a /ts who commad that shows owners an members, so that players can double check who they added anyway.


Finally, I think there are other todo entries under 'Planned', but I may be wrong. Since I won't be home for a while,
I can only review changes but cannot actually commit, so, if you feel like adding it, I hardly have any complaints. Don't feel obligated to, though.

2017-08-04 17:41 UTC, KillerOfPie commented
getShopMembers only returns members now, if you want everything I added a getShopUsers method,
and ill start working on the stuff but if you can get 1.5.2 out it would be nice

2017-08-05 13:22 UTC, SparklingComet commented on src/main/java/org/shanerx/tradeshop/Utils.java
> +            if (m.startsWith("m:")) {
I am sure this used to be different. The if chrck should be removed before merging. Another method returning both owners and members is useless.

2017-08-05 13:26 UTC, SparklingComet commented
> getShopMembers only returns members now, if you want everything I added a getShopUsers method,
and ill start working on the stuff but if you can get 1.5.2 out it would be nice

I agree about the 1.5 part.

2017-08-07 21:49 UTC, KillerOfPie commented
had to remake the 1.6 branch to catch it up to master

2017-08-08 02:04 UTC, KillerOfPie commented
This is working at this point there is a problem that must be addressed before it can be released though.
If a player that is not a owner on the shop puts a sign next to the chest it will add them to the chest(or make it theirs)

2017-08-08 16:33 UTC, SparklingComet commented
Sounds nasty, but should be easy and quick to fix. Just check whether getShopSign returns a valid sign and, if yes, cancel the event with a kind message.
Is it safe to assume that the new patches are working?

2017-08-08 20:40 UTC, SparklingComet commented
> Looks good, gonna test everything real quick and see how many names we can put in

Anything new about that? We need to implement a limit for that.

2017-08-08 22:15 UTC, KillerOfPie commented
@SparklingComet already in max default users is 5

2017-08-08 22:16 UTC, KillerOfPie commented
@SparklingComet problem needs to get fixed for double chests too

2017-08-08 23:34 UTC, SparklingComet commented
I'll add a short checklist to track stuff to change/fic:
- [ ] Stop non-owners to place (trade)signs on shop chests
- [ ] Locking of doublechests needs to be fixed (?) (Found it in the todo list)

2017-08-11 12:55 UTC, SparklingComet commented
I'm merging this into ``1.6`` because this is going beyond this PR's scope.

2017-08-11 12:55 UTC, merged

2017-08-11 12:57 UTC, SparklingComet commented
All fixes need to be pushed to ``1.6-fixes``.

2017-08-11 23:04 UTC, KillerOfPie commented
@SparklingComet changes introduced in 1.5.2 were already merged and all errors from the were fixed

2017-08-12 11:34 UTC, SparklingComet commented
@KillerOfPie excellent, I assume it had been tested and everything is working.

I am referencing #21 as it contains fixes for this PR.

2017-08-12 11:35 UTC, KillerOfPie commented
Si